#!/bin/bash

function master_list {
   if [ $# -ge 1 ]
   then
       echo $@
   else
       git config huck.masters
   fi
}

merge_branchs=`master_list $*`
# echo $merge_branchs

current_branch=`git branch --no-color 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
project_dir=`git rev-parse --show-toplevel`
cat "$project_dir/.git/logs/refs/heads/$current_branch"
