#!/bin/bash

if [ $# -ne 2 ]; then
    echo 'Useage: git view <commit object>  <file path>'
    exit -1
fi

FOBJ=$1:`git rev-parse --show-prefix`$2
FOUT=`mktemp`.`basename $2`
WOUT=`cygpath -p $FOUT -a -w 2>/dev/null`
ISCYGENV=$?

git cat-file -p $FOBJ > $FOUT

if [ $ISCYGENV -eq 0 ]; then
    vi $FOUT
#    start $WOUT
#    sleep 2
else
    vi $FOUT
fi

rm $FOUT

