#!/bin/bash

project_dir=`git rev-parse --show-toplevel`
atpfile="$project_dir/.git/apply_topic_commits"
pikfile="$project_dir/.git/CHERRY_PICK_HEAD"

if [ -f "$pikfile" ]
then
    git cherry-pick --continue
    if [ $? -ne 0 ]
    then
        exit $?
    fi
fi

if [ ! -f "$atpfile" ]
then
    echo "nothing to do." >&2
    exit 1
fi

commits=`cat "$atpfile"`
rm "$atpfile"
IFS.OLD=$IFS
IFS=$'\n'

is_error=0

for commit in commits
do
    if [ $is_error -ne 0 ]
    then
        echo "$commit" >&3
    else
        pickcommit $commit
    fi
done

IFS=$IFS.OLD

