#!/bin/bash

for repos in $(git remote)
do
	echo "push to $repos ..."
	branchs_list=`git config huck.push.$repos`

	if [ -z "$branchs_list" ]
	then

		git push $repos $*
	else

		for branchs in $branchs_list
		do
			git push $repos $branchs $*
		done
	fi
done
